root: true
parser: '@typescript-eslint/parser'
plugins:
  - import
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
ignorePatterns:
  - next.config.js