name: Playwright Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        timeout-minutes: 20
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  lfs: true

            - uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Enable Corepack
              run: corepack enable

            - name: Install dependencies
              run: pnpm install

            - name: Install Playwright Browsers
              run: pnpm exec playwright install --with-deps chromium

            - name: Build App
              run: pnpm build

            - name: Run Playwright tests
              run: pnpm test

            - uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: playwright-report
                  path: |
                      playwright-report/
                      test-results/
                  retention-days: 5
