name: Update Snapshots

on:
    workflow_dispatch:
        inputs:
            message:
                description: 'Commit message'
                required: false
                default: 'chore: update snapshots'

jobs:
    update_snaphots:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  lfs: true

            - uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Enable Corepack
              run: corepack enable

            - name: Install dependencies
              run: pnpm install

            - name: Install Playwright Browsers
              run: pnpm exec playwright install --with-deps chromium

            - name: Build App
              run: pnpm build

            - name: Update snapshots
              run: pnpm exec playwright test --update-snapshots

            - uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: playwright-report
                  path: |
                      playwright-report/
                      test-results/
                  retention-days: 5

            - name: Commit snapshots
              run: |
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "GitHub Actions"
                  git add .
                  git commit -m "${{ github.event.inputs.message }}"
                  git push
